### ISSUE TITLE
Ask for original data

### ISSUE THREAD

**Issue by kimwj94** [sivaramakrishnan-rajaraman/CXR-bone-suppression#2]
Hi, thank you for your research.

> Bone Suppression Dataset:
The researchers from the Budapest University of Technology and Economics used their in-house clavicle and rib–shadow removal algorithms to suppress the bones in the 247 JSRT CXRs and made the bone-suppressed soft-tissue images publicly available at https://www.mit.bme.hu/eng/events/2013/04/18/boneshadow-eliminated-images-jsrt-database. The link is currently broken. We have augmented this dataset to create 4000+ original-bone-suppressed image pairs to train our proposed bone suppression models. The data is available at https://drive.google.com/drive/folders/1m4hlwglZIK14Mlkjf3YsNHRfXLJlfbBN?usp=sharing. Please cite our study if using these data and codes for your research:

I can get 4000+ augmented bone suppression data from the google drive link, but can I get original 247 CXR dataset that before augmented?

I need original dataset because when I tried to split 4000+ augmented dataset into train/val/test datasets, differently augmented images from same original image go to both train set and test set. That causes abnormally high test accuracy.

**Comment by AshleyM0906** [comment]
Hi, may I ask how did you get the class label of the 4000+ augmented bone suppression data? Thank you.

**Comment by sivaramakrishnan-rajaraman** [comment]
I am not sure why you need the class labels for bone suppression. We train the models on bone-suppressed and non-bone-suppressed image pairs so the model predicts a bone-suppressed image when a non-bone-suppressed image is fed into it.

**Comment by sivaramakrishnan-rajaraman** [comment]
> Hi, thank you for your research.
> 
> > Bone Suppression Dataset:
> > The researchers from the Budapest University of Technology and Economics used their in-house clavicle and rib–shadow removal algorithms to suppress the bones in the 247 JSRT CXRs and made the bone-suppressed soft-tissue images publicly available at https://www.mit.bme.hu/eng/events/2013/04/18/boneshadow-eliminated-images-jsrt-database. The link is currently broken. We have augmented this dataset to create 4000+ original-bone-suppressed image pairs to train our proposed bone suppression models. The data is available at https://drive.google.com/drive/folders/1m4hlwglZIK14Mlkjf3YsNHRfXLJlfbBN?usp=sharing. Please cite our study if using these data and codes for your research:
> 
> I can get 4000+ augmented bone suppression data from the google drive link, but can I get original 247 CXR dataset that before augmented?
> 
> I need original dataset because when I tried to split 4000+ augmented dataset into train/val/test datasets, differently augmented images from same original image go to both train set and test set. That causes abnormally high test accuracy.

**Comment by sivaramakrishnan-rajaraman** [comment]
Thanks for your interest in our study. The JSRT dataset (247 CXR images) can be downloaded from http://db.jsrt.or.jp/eng.php. There is also a Kaggle source https://www.kaggle.com/datasets/raddar/nodules-in-chest-xrays-jsrt?select=images where the data is available. Hope this helps.
